version: "3"
services:
    tracing:
        image: jaegertracing/all-in-one
        container_name: jaeger
        ports:
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus
            - ./prometheus-data:/prometheus
