version: "3"
services:
    loki:
        image: grafana/loki:main-5206e3a
        networks:
            - monitoring

    grafana:
        image: grafana/grafana:8.5.3
        ports:
            - "3000:3000"
        environment:
            GF_RENDERING_SERVER_URL: http://renderer:8081/render
            GF_RENDERING_CALLBACK_URL: http://grafana:3000/
            GF_LOG_FILTERS: rendering:debug
        volumes:
            - ./grafana-data:/var/lib/grafana
            - ./grafana/dashboards:/var/lib/grafana/dashboards
            - ./grafana/provisioning:/etc/grafana/provisioning
        networks:
            - monitoring

    renderer:
        image: grafana/grafana-image-renderer:3.4.2
        environment:
            ENABLE_METRICS: "true"
        networks:
            - monitoring

    fluent-bit:
        image: grafana/fluent-bit-plugin-loki:main-5206e3a-amd64
        environment:
            - LOKI_URL=http://loki:3100/loki/api/v1/push
        volumes:
            - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
        ports:
            - "24224:24224"
            - "24224:24224/udp"
        networks:
            - monitoring

    tracing:
        image: jaegertracing/all-in-one
        container_name: jaeger
        ports:
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
        networks:
            - monitoring

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus
            - ./prometheus-data:/prometheus
        networks:
            - monitoring

    node-exporter:
        image: prom/node-exporter:v1.1.2
        ports:
            - "9100:9100"
        networks:
            - monitoring

    cadvisor:
        image: google/cadvisor:v0.33.0
        ports:
            - "8080:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - monitoring

volumes:
    grafana:
        name: grafana
    prometheus:
        name: prometheus

networks:
    monitoring:
        name: monitoring
