name: PR workflow

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Build
              run: go build -v ./...

    test:
        runs-on: ubuntu-latest
        needs: build

        services:
            postgres:
                image: postgres:13.3
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_DB: UserServiceDB
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Test
              env:
                  DATABASE_USER: postgres
                  DATABASE_PASSWORD: postgres
              run: go test -v ./...
