name: Push workflow
permissions: write-all
on:
    push:
         branches:
             - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Build
              run: go build -v ./...

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Test
              run: go test -v ./...
    analyze:
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
            - uses: actions/checkout@v3

            # Initializes the CodeQL tools for scanning.
            # https://github.com/github/codeql-action
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with:
                  languages: go

            # Autobuild attempts to build any compiled languages
            - name: Autobuild
              uses: github/codeql-action/autobuild@v2

            # Perform GitHub Code Scanning.
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2
    release:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Release
              id:   semantic
              uses: codfish/semantic-release-action@v2.0.0
              with:
                branches: |
                  [
                   'main',
                   'feature-github-actions',
                   'develop'
                  ]
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              env:
                OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
              with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/windbnb-user-service:${{ steps.semantic.outputs.release-version }},${{ secrets.DOCKERHUB_USERNAME }}/windbnb-user-service:latest
                  cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/windbnb-user-service:latest
